[target.wasm32v1-none]
# A pass-through wrapper around `rust-lld` that runs `wasm-opt` over the module
# it produces, for release builds only.
linker = "tools/wasm-link"
rustflags = [
    "-Ctarget-cpu=mvp",
    "-Ctarget-feature=+mutable-globals",
    # TODO(tumbar) We do not support this in spacewasm yet
    # "-Ctarget-feature=+bulk-memory",
    "-Clink-args=-zstack-size=512",
    "-Clink-arg=--page-size=1",
]
